### ISSUE TITLE
Same behavior for "static" image wallpapers (no scheduled slideshow)

### ISSUE THREAD

**Issue by kupiqu** [psifidotos/latte_slideshow_wallpaper#3]
This would use the same set of images than regular plasma image wallpaper, with the advantge that latte colors would adapt on-the-fly to manual wallpaper changes.

**Comment by psifidotos** [comment]
I cant understand what you are describing

**Comment by kupiqu** [comment]
I think this is default behavior, as I can see how colors are changing according to background color when I change the wallpaper.

- I see however an issue, while white text color on dark background shows a good contrast, dark text color on light backgrounds is not as good as it could be. Or perhaps it's that I need to tweak some setting in latte.

![image](https://user-images.githubusercontent.com/3875196/69495637-1dbd0980-0e97-11ea-81bd-1fa8dcef6866.png)

- Also, it would be great to have the same functionality of plasma-systray-latte-tweaks applied elsewhere, that is the possibility to tell latte do not autocolor certain applets because they look bad.

I close this issue because it does not apply here, but these two issues above make me not using autocolor in a regular basis. Is there a place where I could submit these issues?

**Comment by kupiqu** [comment]
> Also, it would be great to have the same functionality of plasma-systray-latte-tweaks applied elsewhere, that is the possibility to tell latte do not autocolor certain applets because they look bad.

Nevermind, I discovered how to do it, my bad...
